### ISSUE TITLE
Space Invaders (pen project)

### ISSUE THREAD

**Issue by BenHunter69** [ilovecode1/Phosphorus-Plus-2.0#7]
Just blank???
http://scratch.mit.edu/projects/102605073/
http://phosphorus.github.io/#102605073
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by CosmicWebServices** [comment]
That is phosphorus on Phosphorus+ http://cosmicsearch.org/Phosphorus+/#102605073
